export const brandDictionary: Record<string, string[]> = {
  "Amiri":              ["am*ri", "a*iri", "amiri"],
  "Balenciaga":         ["balen*iaga", "b*lenciaga", "balenciaga", "bal*nciaga"],
  "Bottega Veneta":     ["bottega ven*ta", "bott*ga veneta", "bottega", "bv"],
  "Burberry":           ["burb*rry", "b*rberry", "burberry"],
  "Celine":             ["cel*ne", "c*line", "celine"],
  "Chanel":             ["chan*l", "ch*nel", "chanel"],
  "Chrome Hearts":      ["chrome he*rts", "chr*me hearts", "chrome hearts"],
  "Dior":               ["d*or", "di*r", "dior", "christian dior"],
  "Dolce & Gabbana":    ["dolce gabb*na", "d*g", "dolce & gabbana", "d&g"],
  "Fendi":              ["fend*", "f*ndi", "fendi"],
  "Givenchy":           ["giv*nchy", "g*venchy", "givenchy"],
  "Gucci":              ["gucc*", "g*cci", "gucci"],
  "Hermès":             ["herm*s", "h*rmes", "hermes"],
  "Loewe":              ["loew*", "l*ewe", "loewe"],
  "Louis Vuitton":      ["louis vu*tton", "l*uis vuitton", "lv", "louis vuitton"],
  "Maison Margiela":    ["maison marg*ela", "m*rgiela", "margiela"],
  "Moncler":            ["monc*er", "m*ncler", "moncler"],
  "Prada":              ["prad*", "p*ada", "prada"],
  "Rick Owens":         ["rick ow*ns", "r*ck owens", "rick owens"],
  "Valentino":          ["valent*no", "v*lentino", "valentino"],
  "Versace":            ["vers*ce", "v*rsace", "versace"],
  "Yves Saint Laurent": ["ysl", "saint laur*nt", "yves saint laurent"],
  "Vetements":          ["vetem*nts", "v*tements", "vetements"],
  "A Bathing Ape":      ["bape", "a bath*ng ape", "a bathing ape"],
  "Anti Social Social Club": ["assc", "anti soc*al", "anti social social club"],
  "Carhartt":           ["carhar*t", "c*rhartt", "carhartt"],
  "Corteiz":            ["cort*iz", "c*rteiz", "corteiz", "crtz"],
  "Cpfm":               ["cpfm", "cactus plant", "cactus pl*nt"],
  "Denim Tears":        ["denim te*rs", "d*nim tears", "denim tears"],
  "Drew House":         ["drew hous*", "dr*w house", "drew house"],
  "Eric Emanuel":       ["eric eman*el", "e*ic emanuel", "eric emanuel"],
  "Essentials":         ["ess*ntials", "e*sentials", "fear of god", "fog"],
  "Gallery Dept":       ["gallery d*pt", "gall*ry dept", "gallery dept"],
  "Hellstar":           ["hellst*r", "h*llstar", "hellstar"],
  "Human Made":         ["human mad*", "h*man made", "human made"],
  "Kith":               ["kit*", "k*th", "kith"],
  "Madhappy":           ["madh*ppy", "m*dhappy", "madhappy"],
  "New Balance":        ["new balan*e", "n*w balance", "new balance"],
  "Nike":               ["nik*", "n*ke", "nike"],
  "Adidas":             ["adid*s", "a*idas", "adidas"],
  "Off-White":          ["off wh*te", "o*f white", "off-white", "offwhite"],
  "Palm Angels":        ["palm *ngels", "p*lm angels", "palm angels"],
  "Rhude":              ["rhud*", "r*ude", "rhude"],
  "Stone Island":       ["stone isl*nd", "st*ne island", "stone island"],
  "Stussy":             ["stuss*", "st*ssy", "stussy"],
  "Supreme":            ["supr*me", "s*preme", "supreme"],
  "Trapstar":           ["trap*tar", "tr*pstar", "trapstar"],
  "Undercover":         ["undercov*r", "u*dercover", "undercover"],
  "Jordan":             ["jord*n", "j*rdan", "jordan", "air jordan"],
  "Puma":               ["pum*", "p*ma", "puma"],
  "Reebok":             ["reeb*k", "r*ebok", "reebok"],
  "Under Armour":       ["under arm*ur", "u*der armour", "under armour"],
  "Travis Scott":       ["travis sc*tt", "travis scott", "cactus jack"],
  "Kanye West":         ["kanye", "yeezy", "yeez*", "k*nye"],
  "Drake / OVO":        ["ovo", "october very own", "drake"],
  "Juice WRLD":         ["juice wrld", "999"],
  "Playboi Carti":      ["carti", "playboi cart*", "opium"],
  "Vlone":              ["vlon*", "v*lone", "vlone"],
  "Sp5der":             ["sp5d*r", "sp5der", "spider"],
  "Broken Planet":      ["broken plan*t", "broken planet"],
  "Revenge":            ["reveng*", "r*venge", "revenge"],
  "Levi's":             ["levi*", "l*vis", "levis"],
  "Dickies":            ["dicki*s", "d*ckies", "dickies"],
  "Asics":              ["asic*", "a*ics", "asics"],
  "Converse":           ["convers*", "c*nverse", "converse"],
  "Vans":               ["van*", "v*ns", "vans"],
  "Timberland":         ["timberlan*", "t*mberland", "timberland"],
  "Rolex":              ["role*", "r*lex", "rolex"],
  "Audemars Piguet":    ["audemars", "audema*s", "royal oak"],
  "Richard Mille":      ["richard mill*", "richard mille", "rm*"],
  "Cartier":            ["cartie*", "c*rtier", "cartier", "c*r*i*r"],
};
